site_name: Django Blog

nav:
  - Home: index.md
  - About: about.md
  - Tutorial:
      - Introduction: tutorial/Introduction.md
      - Installation: tutorial/Installation.md
      - REST API: tutorial/Restapi.md
      - Conclusion: tutorial/Conclusion.md
